topic_camera: "/dope/webcam/image_raw"
topic_camera_info: "/dope/webcam/camera_info"
topic_publishing: "dope"
input_is_rectified: True   # Whether the input image is rectified (strongly suggested!)
downscale_height: 400      # if the input image is larger than this, scale it down to this pixel height

# Comment any of these lines to prevent detection / pose estimation of that object
weights: {
    "reinforced_bracket":"package://dope/myscripts/weights/net_rb_70k_3.pth",
}

# Cuboid dimension in cm x,y,z
# From meshlab tCuboid dimension in cm y,z,x
dimensions: {
    "reinforced_bracket": [6.7643, 4.8871, 12.8142],    
}

class_ids: {
    "reinforced_bracket": 0,
}

draw_colors: {
    "reinforced_bracket": [255, 0, 0],  # red
}

# optional: If the specified meshes are not in meters, provide a scale here (e.g. if the mesh is in centimeters, scale should be 0.01). default scale: 1.0.
mesh_scales: {
    "reinforced_bracket":  0.01,
}

overlay_belief_images: True   # Whether to overlay the input image on the belief images published on /dope/belief_[obj_name]

# Config params for DOPE
thresh_angle: 0.5
thresh_map: 0.01
sigma: 3
thresh_points: 0.1
